
version: "3"

services:
  front:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "4200:80"


  mysqldb:
    image: mysql
    restart: unless-stopped
    # env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    volumes:
      - dbtoubibnet:/var/lib/mysql


  app:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: ./back-api.dockerfile
    # env_file: ./.env
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PORT=3306




volumes:
  dbtoubibnet:

